const namesOfAllah = [
  { arabic: "الرَّحْمَٰنُ", meaning: "The Most Compassionate", arabicExplanation: "الأشد رحمة" },
  { arabic: "الرَّحِيمُ", meaning: "The Most Merciful", arabicExplanation: "الأرحم بعباده" },
  { arabic: "الْمَلِكُ", meaning: "The King", arabicExplanation: "الملك المتصرف في كل شيء" },
  { arabic: "الْقُدُّوسُ", meaning: "The Most Holy", arabicExplanation: "المنزه عن كل نقص" },
  { arabic: "السَّلَامُ", meaning: "The Source of Peace", arabicExplanation: "مانح السلام والأمان" },
  { arabic: "الْمُؤْمِنُ", meaning: "The Granter of Security", arabicExplanation: "مؤمن الخلق من الخوف" },
  { arabic: "الْمُهَيْمِنُ", meaning: "The Guardian", arabicExplanation: "الرقيب الحافظ" },
  { arabic: "الْعَزِيزُ", meaning: "The Almighty", arabicExplanation: "العزيز الذي لا يغلب" },
  { arabic: "الْجَبَّارُ", meaning: "The Compeller", arabicExplanation: "الجبار الذي يقهر الخلق على ما أراد" },
  { arabic: "الْمُتَكَبِّرُ", meaning: "The Supremely Great", arabicExplanation: "المتكبر العظيم المتعالي" },
  { arabic: "الْخَالِقُ", meaning: "The Creator", arabicExplanation: "الخالق لكل شيء" },
  { arabic: "الْبَارِئُ", meaning: "The Originator", arabicExplanation: "المبدئ للخلق" },
  { arabic: "الْمُصَوِّرُ", meaning: "The Fashioner", arabicExplanation: "المصور الذي أعطى كل شيء صورته" },
  { arabic: "الْغَفَّارُ", meaning: "The Ever-Forgiving", arabicExplanation: "كثير المغفرة" },
  { arabic: "الْقَهَّارُ", meaning: "The All-Dominant", arabicExplanation: "القهار الغالب لكل شيء" },
  { arabic: "الْوَهَّابُ", meaning: "The Supreme Bestower", arabicExplanation: "كثير العطاء بلا مقابل" },
  { arabic: "الرَّزَّاقُ", meaning: "The Provider", arabicExplanation: "كثير الرزق" },
  { arabic: "الْفَتَّاحُ", meaning: "The Opener", arabicExplanation: "الفاتح لأبواب الخير والحكم" },
  { arabic: "اَلْعَلِيْمُ", meaning: "The All-Knowing", arabicExplanation: "العالم بكل شيء" },
  { arabic: "الْقَابِضُ", meaning: "The Withholder", arabicExplanation: "القابض للأرزاق والأرواح" },
  { arabic: "الْبَاسِطُ", meaning: "The Extender", arabicExplanation: "الباسط للرزق والرحمة" },
  { arabic: "الْخَافِضُ", meaning: "The Reducer", arabicExplanation: "الخافض لمن يشاء" },
  { arabic: "الرَّافِعُ", meaning: "The Exalter", arabicExplanation: "الرافع لمن يشاء" },
  { arabic: "الْمُعِزُّ", meaning: "The Honourer", arabicExplanation: "المعز لمن يشاء" },
  { arabic: "المُذِلُّ", meaning: "The Humiliator", arabicExplanation: "المذل لمن يشاء" },
  { arabic: "السَّمِيعُ", meaning: "The All-Hearing", arabicExplanation: "السميع لكل الأصوات" },
  { arabic: "الْبَصِيرُ", meaning: "The All-Seeing", arabicExplanation: "البصير بكل الأشياء" },
  { arabic: "الْحَكَمُ", meaning: "The Judge", arabicExplanation: "الحكم بين عباده بالحق" },
  { arabic: "الْعَدْلُ", meaning: "The Utterly Just", arabicExplanation: "العدل الكامل" },
  { arabic: "اللَّطِيفُ", meaning: "The Subtle One", arabicExplanation: "اللطيف بعباده" },
  { arabic: "الْخَبِيرُ", meaning: "The All-Aware", arabicExplanation: "الخبير بدقائق الأمور" },
  { arabic: "الْحَلِيمُ", meaning: "The Most Forbearing", arabicExplanation: "الحليم الذي لا يعجل بالعقوبة" },
  { arabic: "الْعَظِيمُ", meaning: "The Magnificent", arabicExplanation: "العظيم الذي لا يحيط به وصف" },
  { arabic: "الْغَفُورُ", meaning: "The Great Forgiver", arabicExplanation: "الغفور واسع المغفرة" },
  { arabic: "الشَّكُورُ", meaning: "The Most Appreciative", arabicExplanation: "الشكور الذي يثيب على القليل" },
  { arabic: "الْعَلِيُّ", meaning: "The Most High", arabicExplanation: "العلي المرتفع فوق كل شيء" },
  { arabic: "الْكَبِيرُ", meaning: "The Most Great", arabicExplanation: "الكبير الذي كل شيء دونه" },
  { arabic: "الْحَفِيظُ", meaning: "The Preserver", arabicExplanation: "الحفيظ الحافظ لكل شيء" },
  { arabic: "المُقيِت", meaning: "The Sustainer", arabicExplanation: "المقيت الممد بالقوت" },
  { arabic: "الْحسِيبُ", meaning: "The Reckoner", arabicExplanation: "الحسيب الكافي والمحاسب" },
  { arabic: "الْجَلِيلُ", meaning: "The Majestic", arabicExplanation: "الجليل ذو الجلال" },
  { arabic: "الْكَرِيمُ", meaning: "The Most Generous", arabicExplanation: "الكريم كثير الإحسان" },
  { arabic: "الرَّقِيبُ", meaning: "The Watchful", arabicExplanation: "الرقيب الذي لا يغيب عنه شيء" },
  { arabic: "الْمُجِيبُ", meaning: "The Responsive One", arabicExplanation: "المجيب للدعاء" },
  { arabic: "الْوَاسِعُ", meaning: "The All-Encompassing", arabicExplanation: "الواسع الذي وسع كل شيء" },
  { arabic: "الْحَكِيمُ", meaning: "The All-Wise", arabicExplanation: "الحكيم الذي يضع الأمور مواضعها" },
  { arabic: "الْوَدُودُ", meaning: "The Most Loving", arabicExplanation: "الودود كثير المحبة لعباده" },
  { arabic: "الْمَجِيدُ", meaning: "The Most Glorious", arabicExplanation: "المجيد كامل الشرف والمجد" },
  { arabic: "الْبَاعِثُ", meaning: "The Resurrector", arabicExplanation: "الباعث الذي يبعث الخلق" },
  { arabic: "الشَّهِيدُ", meaning: "The Witness", arabicExplanation: "الشهيد الذي لا يغيب عنه شيء" },
  { arabic: "الْحَقُّ", meaning: "The Absolute Truth", arabicExplanation: "الحق الثابت الذي لا شك فيه" },
  { arabic: "الْوَكِيلُ", meaning: "The Trustee", arabicExplanation: "الوكيل الكفيل بأمور عباده" },
  { arabic: "الْقَوِيُّ", meaning: "The All-Strong", arabicExplanation: "القوي كامل القوة" },
  { arabic: "الْمَتِينُ", meaning: "The Firm One", arabicExplanation: "المتين شديد القوة" },
  { arabic: "الْوَلِيُّ", meaning: "The Protecting Friend", arabicExplanation: "الولي الناصر المتولي لعباده" },
  { arabic: "الْحَمِيدُ", meaning: "The Praiseworthy", arabicExplanation: "الحميد المستحق لكل حمد" },
  { arabic: "الْمُحْصِي", meaning: "The Accounter", arabicExplanation: "المحصي الذي أحصى كل شيء عددا" },
  { arabic: "الْمُبْدِئُ", meaning: "The Originator", arabicExplanation: "المبدئ للخلق ابتداء" },
  { arabic: "الْمُعِيدُ", meaning: "The Restorer", arabicExplanation: "المعيد الذي يعيد الخلق بعد الموت" },
  { arabic: "الْمُحْيِي", meaning: "The Giver of Life", arabicExplanation: "المحيي واهب الحياة" },
  { arabic: "اَلْمُمِيتُ", meaning: "The Creator of Death", arabicExplanation: "المميت الذي يقدر الموت" },
  { arabic: "الْحَيُّ", meaning: "The Ever-Living", arabicExplanation: "الحي الذي لا يموت" },
  { arabic: "الْقَيُّومُ", meaning: "The Self-Subsisting", arabicExplanation: "القيوم القائم بنفسه المقيم لغيره" },
  { arabic: "الْوَاجِدُ", meaning: "The Finder", arabicExplanation: "الواجد الذي لا يعجزه شيء" },
  { arabic: "الْمَاجِدُ", meaning: "The Noble", arabicExplanation: "الماجد العظيم الكريم" },
  { arabic: "الْواحِدُ", meaning: "The One", arabicExplanation: "الواحد المنفرد" },
  { arabic: "اَلاَحَدُ", meaning: "The Unique", arabicExplanation: "الأحد الذي لا نظير له" },
  { arabic: "الصَّمَدُ", meaning: "The Eternal Refuge", arabicExplanation: "الصمد المقصود في الحوائج" },
  { arabic: "الْقَادِرُ", meaning: "The All-Powerful", arabicExplanation: "القادر على كل شيء" },
  { arabic: "الْمُقْتَدِرُ", meaning: "The Creator of All Power", arabicExplanation: "المقتدر كامل القدرة" },
  { arabic: "الْمُقَدِّمُ", meaning: "The Expediter", arabicExplanation: "المقدم الذي يقدم من يشاء" },
  { arabic: "الْمُؤَخِّرُ", meaning: "The Delayer", arabicExplanation: "المؤخر الذي يؤخر من يشاء" },
  { arabic: "الأوَّلُ", meaning: "The First", arabicExplanation: "الأول الذي ليس قبله شيء" },
  { arabic: "الآخِرُ", meaning: "The Last", arabicExplanation: "الآخر الذي ليس بعده شيء" },
  { arabic: "الظَّاهِرُ", meaning: "The Manifest", arabicExplanation: "الظاهر العالي فوق خلقه" },
  { arabic: "الْبَاطِنُ", meaning: "The Hidden One", arabicExplanation: "الباطن القريب الذي أحاط بكل شيء" },
  { arabic: "الْوَالِي", meaning: "The Sole Governor", arabicExplanation: "الوالي المتولي لجميع الأمور" },
  { arabic: "الْمُتَعَالِي", meaning: "The Most Exalted", arabicExplanation: "المتعالي المنزه عن مشابهة الخلق" },
  { arabic: "الْبَرُّ", meaning: "The Source of Goodness", arabicExplanation: "البر كثير الإحسان" },
  { arabic: "التَّوَابُ", meaning: "The Accepter of Repentance", arabicExplanation: "التواب الذي يقبل التوبة" },
  { arabic: "الْمُنْتَقِمُ", meaning: "The Avenger", arabicExplanation: "المنتقم ممن يستحق العقوبة" },
  { arabic: "العَفُوُّ", meaning: "The Pardoner", arabicExplanation: "العفو الذي يمحو الذنوب" },
  { arabic: "الرَّؤُوفُ", meaning: "The Most Kind", arabicExplanation: "الرؤوف شديد الرحمة" },
  { arabic: "مَالِكُ الْمُلْكِ", meaning: "Master of the Kingdom", arabicExplanation: "مالك الملك المتصرف في الملك كله" },
  { arabic: "ذُوالْجَلَالِ وَالإكْرَامِ", meaning: "Possessor of Majesty and Honor", arabicExplanation: "ذو الجلال والإكرام صاحب العظمة والكرم" },
  { arabic: "الْمُقْسِطُ", meaning: "The Equitable", arabicExplanation: "المقسط العادل المنصف" },
  { arabic: "الْجَامِعُ", meaning: "The Gatherer", arabicExplanation: "الجامع الذي يجمع الخلق" },
  { arabic: "الْغَنِيُّ", meaning: "The Self-Sufficient", arabicExplanation: "الغني الذي لا يحتاج إلى أحد" },
  { arabic: "الْمُغْنِي", meaning: "The Enricher", arabicExplanation: "المغني الذي يغني من يشاء" },
  { arabic: "اَلْمَانِعُ", meaning: "The Withholder", arabicExplanation: "المانع الذي يمنع ما يشاء" },
  { arabic: "الضَّارَ", meaning: "The Distresser", arabicExplanation: "الضار الذي يقدر الضرر بحكمة" },
  { arabic: "النَّافِعُ", meaning: "The Propitious", arabicExplanation: "النافع الذي يقدر النفع" },
  { arabic: "النُّورُ", meaning: "The Light", arabicExplanation: "النور المنير للقلوب والكون" },
  { arabic: "الْهَادِي", meaning: "The Guide", arabicExplanation: "الهادي إلى الصراط المستقيم" },
  { arabic: "الْبَدِيعُ", meaning: "The Incomparable Originator", arabicExplanation: "البديع المبدع بلا مثال" },
  { arabic: "الْبَاقِي", meaning: "The Everlasting", arabicExplanation: "الباقي الذي لا يفنى" },
  { arabic: "الْوَارِثُ", meaning: "The Inheritor", arabicExplanation: "الوارث الذي يرث الأرض ومن عليها" },
  { arabic: "الرَّشِيدُ", meaning: "The Guide to the Right Path", arabicExplanation: "الرشيد الهادي إلى الصواب" },
  { arabic: "الصَّبُورُ", meaning: "The Most Patient", arabicExplanation: "الصبور الذي لا يعجل بالعقوبة" }
];

const STORAGE_KEY = "namesMemorizationV1";
const MILLISECONDS_PER_DAY = 24 * 60 * 60 * 1000;
const QUIZ_ACTION_COOLDOWN_MS = 150;

window.appConstants = {
  namesOfAllah,
  STORAGE_KEY,
  MILLISECONDS_PER_DAY,
  QUIZ_ACTION_COOLDOWN_MS
};
